use components

db.getCollection('configurations').insertMany([
  {
    "name": "Ma super Config 1",
    "processor": "Intel Core I7-820",
    "cooler": "cooler1",
    "motherboard": "motherboard",
    "ram": "ram",
    "graphic_card": "graphicCard",
    "ssd": "SSD",
    "hard_drive": "HardDrive",
    "case": "case",
    "power_supply_unit": "PowerUnit",
    "sound_card": "SoundCard",
    "network_adapter": "Adapter"
  },
  {
    "name": "Ma super Config 2",
    "processor": "Intel Core I7-820",
    "cooler": "cooler1",
    "motherboard": "motherboard",
    "ram": "ram",
    "graphic_card": "graphicCard",
    "ssd": "SSD",
    "hard_drive": "HardDrive",
    "case": "case",
    "power_supply_unit": "PowerUnit",
    "sound_card": "SoundCard",
    "network_adapter": "Adapter"
  },
  {
    "name": "Ma super Config 3",
    "processor": "Intel Core I7-820",
    "cooler": "cooler1",
    "motherboard": "motherboard",
    "ram": "ram",
    "graphic_card": "graphicCard",
    "ssd": "SSD",
    "hard_drive": "HardDrive",
    "case": "case",
    "power_supply_unit": "PowerUnit",
    "sound_card": "SoundCard",
    "network_adapter": "Adapter"
  },
  {
    "name": "Ma super Config 4",
    "processor": "Intel Core I7-820",
    "cooler": "cooler1",
    "motherboard": "motherboard",
    "ram": "ram",
    "graphic_card": "graphicCard",
    "ssd": "SSD",
    "hard_drive": "HardDrive",
    "case": "case",
    "power_supply_unit": "PowerUnit",
    "sound_card": "SoundCard",
    "network_adapter": "Adapter"
  },
  {
    "name": "Ma super Config 5",
    "processor": "Intel Core I7-820",
    "cooler": "cooler1",
    "motherboard": "motherboard",
    "ram": "ram",
    "graphic_card": "graphicCard",
    "ssd": "SSD",
    "hard_drive": "HardDrive",
    "case": "case",
    "power_supply_unit": "PowerUnit",
    "sound_card": "SoundCard",
    "network_adapter": "Adapter"
  },
  {
    "name": "Ma super Config 6",
    "processor": "Intel Core I7-820",
    "cooler": "cooler1",
    "motherboard": "motherboard",
    "ram": "ram",
    "graphic_card": "graphicCard",
    "ssd": "SSD",
    "hard_drive": "HardDrive",
    "case": "case",
    "power_supply_unit": "PowerUnit",
    "sound_card": "SoundCard",
    "network_adapter": "Adapter"
  },
  {
    "name": "Ma super Config 7",
    "processor": "Intel Core I7-820",
    "cooler": "cooler1",
    "motherboard": "motherboard",
    "ram": "ram",
    "graphic_card": "graphicCard",
    "ssd": "SSD",
    "hard_drive": "HardDrive",
    "case": "case",
    "power_supply_unit": "PowerUnit",
    "sound_card": "SoundCard",
    "network_adapter": "Adapter"
  },
  {
    "name": "Ma super Config 8",
    "processor": "Intel Core I7-820",
    "cooler": "cooler1",
    "motherboard": "motherboard",
    "ram": "ram",
    "graphic_card": "graphicCard",
    "ssd": "SSD",
    "hard_drive": "HardDrive",
    "case": "case",
    "power_supply_unit": "PowerUnit",
    "sound_card": "SoundCard",
    "network_adapter": "Adapter"
  },
  {
    "name": "Ma super Config 9",
    "processor": "Intel Core I7-820",
    "cooler": "cooler1",
    "motherboard": "motherboard",
    "ram": "ram",
    "graphic_card": "graphicCard",
    "ssd": "SSD",
    "hard_drive": "HardDrive",
    "case": "case",
    "power_supply_unit": "PowerUnit",
    "sound_card": "SoundCard",
    "network_adapter": "Adapter"
  },
])
